import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:provider/provider.dart';
import '../models/task_model.dart';
import '../providers/task_provider.dart';
import '../utils/constants.dart';
import '../widgets/custom_text.dart';

class AddTaskScreen extends StatefulWidget {
  const AddTaskScreen({Key? key}) : super(key: key);

  @override
  State<AddTaskScreen> createState() => _AddTaskScreenState();
}

class _AddTaskScreenState extends State<AddTaskScreen> {
  final _formKey = GlobalKey<FormState>();
  final _titleController = TextEditingController();
  final _descController = TextEditingController();
  DateTime? _selectedDate;
  TimeOfDay? _selectedTime;
  String _selectedPriority = 'High';
  String _selectedCategory = 'Work';

  void _addTask() async {
    if (!_formKey.currentState!.validate()) return;
    if (_selectedDate == null) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Please select a date')));
      return;
    }
    if (_selectedTime == null) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Please select a time')));
      return;
    }

    final newTask = TaskModel(
      id: '', // Will be generated by backend
      title: _titleController.text,
      description: _descController.text,
      date: DateFormat('yyyy-MM-dd').format(_selectedDate!),
      time: '${_selectedTime!.hour.toString().padLeft(2, '0')}:${_selectedTime!.minute.toString().padLeft(2, '0')}',
      priority: _selectedPriority,
      category: _selectedCategory,
    );

    try {
      await context.read<TaskProvider>().addTask(newTask);
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Task added successfully!')));
        Navigator.pop(context);
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(e.toString())));
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final isLoading = context.watch<TaskProvider>().isLoading;

    return Scaffold(
      backgroundColor: AppColors.primary,
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: Colors.white),
          onPressed: () => Navigator.pop(context),
        ),
      ),
      body: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Padding(
            padding: EdgeInsets.symmetric(horizontal: 24.0, vertical: 8.0),
            child: CustomText(
              text: 'Add New Task',
              style: TextStyle(fontSize: 28, fontWeight: FontWeight.bold, color: Colors.white),
            ),
          ),
          const SizedBox(height: 24),
          Expanded(
            child: Container(
              padding: const EdgeInsets.all(24),
              decoration: const BoxDecoration(
                color: Colors.white,
                borderRadius: BorderRadius.only(topLeft: Radius.circular(30), topRight: Radius.circular(30)),
              ),
              child: Form(
                key: _formKey,
                child: SingleChildScrollView(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const CustomText(text: 'Title', style: AppStyles.subtitle),
                      const SizedBox(height: 8),
                      TextFormField(
                        controller: _titleController,
                        decoration: _inputDecoration('e.g. Buy groceries'),
                        validator: (value) => value == null || value.isEmpty ? 'Title is required' : null,
                      ),
                      
                      const SizedBox(height: 16),
                      const CustomText(text: 'Description', style: AppStyles.subtitle),
                      const SizedBox(height: 8),
                      TextFormField(
                        controller: _descController,
                        maxLines: 3,
                        decoration: _inputDecoration('Add a description'),
                      ),
                      
                      const SizedBox(height: 16),
                      const CustomText(text: 'Date & Time', style: AppStyles.subtitle),
                      const SizedBox(height: 8),
                      Row(
                        children: [
                          Expanded(child: _buildDatePicker()),
                          const SizedBox(width: 16),
                          Expanded(child: _buildTimePicker()),
                        ],
                      ),

                      const SizedBox(height: 16),
                      const CustomText(text: 'Priority', style: AppStyles.subtitle),
                      const SizedBox(height: 8),
                      Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: ['High', 'Medium', 'Low'].map((p) => _buildPriorityChip(p)).toList(),
                      ),

                      const SizedBox(height: 16),
                      const CustomText(text: 'Category', style: AppStyles.subtitle),
                      const SizedBox(height: 8),
                      Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          _buildCategoryChip('Work', Icons.work, AppColors.workIcon, AppColors.workBg),
                          _buildCategoryChip('Personal', Icons.person, AppColors.personalIcon, AppColors.personalBg),
                          _buildCategoryChip('Shopping', Icons.shopping_bag, AppColors.shoppingIcon, AppColors.shoppingBg),
                          _buildCategoryChip('Health', Icons.favorite, AppColors.healthIcon, AppColors.healthBg),
                        ],
                      ),

                      const SizedBox(height: 40),
                      SizedBox(
                        width: double.infinity,
                        height: 56,
                        child: ElevatedButton(
                          onPressed: isLoading ? null : _addTask,
                          style: ElevatedButton.styleFrom(
                            backgroundColor: AppColors.primary,
                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
                          ),
                          child: isLoading
                              ? const CircularProgressIndicator(color: Colors.white)
                              : const CustomText(
                                  text: 'Add Task',
                                  style: TextStyle(color: Colors.white, fontSize: 18, fontWeight: FontWeight.bold),
                                ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ),
          )
        ],
      ),
    );
  }

  InputDecoration _inputDecoration(String hint) {
    return InputDecoration(
      hintText: hint,
      hintStyle: AppStyles.subtitle.copyWith(color: AppColors.textSecondary.withOpacity(0.5)),
      filled: true,
      fillColor: AppColors.background,
      border: OutlineInputBorder(borderRadius: BorderRadius.circular(16), borderSide: BorderSide.none),
    );
  }

  Widget _buildDatePicker() {
    return GestureDetector(
      onTap: () async {
        final date = await showDatePicker(
          context: context,
          initialDate: _selectedDate ?? DateTime.now(),
          firstDate: DateTime.now(),
          lastDate: DateTime(2100),
        );
        if (date != null) setState(() => _selectedDate = date);
      },
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 16),
        decoration: BoxDecoration(color: AppColors.background, borderRadius: BorderRadius.circular(16)),
        child: Row(
          children: [
            const Icon(Icons.calendar_today, size: 20, color: AppColors.textSecondary),
            const SizedBox(width: 8),
            Expanded(child: CustomText(
              text: _selectedDate == null ? 'Date' : DateFormat('MMM dd, yyyy').format(_selectedDate!),
              style: AppStyles.body,
              maxLines: 1,
              overflow: TextOverflow.ellipsis,
            )),
          ],
        ),
      ),
    );
  }

  Widget _buildTimePicker() {
    return GestureDetector(
      onTap: () async {
        final time = await showTimePicker(
          context: context,
          initialTime: _selectedTime ?? TimeOfDay.now(),
        );
        if (time != null) setState(() => _selectedTime = time);
      },
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 16),
        decoration: BoxDecoration(color: AppColors.background, borderRadius: BorderRadius.circular(16)),
        child: Row(
          children: [
            const Icon(Icons.access_time, size: 20, color: AppColors.textSecondary),
            const SizedBox(width: 8),
            Expanded(child: CustomText(
              text: _selectedTime == null ? 'Time' : _selectedTime!.format(context),
              style: AppStyles.body,
              maxLines: 1,
              overflow: TextOverflow.ellipsis,
            )),
          ],
        ),
      ),
    );
  }

  Widget _buildPriorityChip(String priority) {
    final isSelected = _selectedPriority == priority;
    Color color = priority == 'High' ? AppColors.highPriority : priority == 'Medium' ? AppColors.mediumPriority : AppColors.lowPriority;

    return GestureDetector(
      onTap: () => setState(() => _selectedPriority = priority),
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 12),
        decoration: BoxDecoration(
          color: isSelected ? color.withOpacity(0.1) : AppColors.background,
          border: Border.all(color: isSelected ? color : Colors.transparent),
          borderRadius: BorderRadius.circular(12),
        ),
        child: Row(
          children: [
            Icon(Icons.circle, size: 12, color: color),
            const SizedBox(width: 8),
            CustomText(
              text: priority,
              style: AppStyles.body.copyWith(
                color: isSelected ? color : AppColors.textPrimary,
                fontWeight: isSelected ? FontWeight.bold : FontWeight.normal,
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildCategoryChip(String category, IconData icon, Color iconColor, Color bgColor) {
    final isSelected = _selectedCategory == category;
    
    return GestureDetector(
      onTap: () => setState(() => _selectedCategory = category),
      child: Column(
        children: [
          Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: bgColor,
              shape: BoxShape.circle,
              border: Border.all(color: isSelected ? iconColor : Colors.transparent, width: 2),
            ),
            child: Icon(icon, color: iconColor),
          ),
          const SizedBox(height: 8),
          CustomText(text: category, style: AppStyles.caption),
        ],
      ),
    );
  }
}
